import type { Version } from "@/lib/db/schema";

/** Renders a pasted-copy version like a printed page / email. HTML is generated by us (escaped), so it is safe to inject. */
export function CopyPreview({ version, className }: { version: Version; className?: string }) {
  const isEmail = !!version.emailSubject || !!version.emailFromName;
  return (
    <div className={className}>
      <article className="mx-auto max-w-2xl rounded-md bg-white px-6 py-8 shadow-sm ring-1 ring-line sm:px-10 sm:py-10">
        {isEmail ? (
          <header className="hairline-b border-line mb-6 pb-4 text-sm">
            {version.emailFromName ? (
              <p className="text-slate">
                From: <span className="text-ink">{version.emailFromName}</span>
              </p>
            ) : null}
            {version.emailSubject ? (
              <p className="mt-1 text-slate">
                Subject: <span className="font-medium text-ink">{version.emailSubject}</span>
              </p>
            ) : null}
          </header>
        ) : null}
        <div
          className="copy-body text-[15px] leading-7 text-ink [&_p]:mb-4 [&_p:last-child]:mb-0"
          dangerouslySetInnerHTML={{ __html: version.emailHtml ?? "" }}
        />
      </article>
    </div>
  );
}
