/**
 * Seeds a demo workspace: 1 owner, 1 designer, 2 projects, fake approvers.
 * Usage: pnpm db:seed   (reads .env; set SEED_OWNER_EMAIL to make yourself the owner)
 */
import "dotenv/config";
import { createHmac, randomBytes } from "node:crypto";
import { addDays, subDays } from "date-fns";
import { eq } from "drizzle-orm";
import { put } from "@vercel/blob";
import { scriptDb, schema } from "./db";

const { users, projects, items, versions, reviewRounds, approvals, comments, activity, settings } = schema;

const secret = process.env.SESSION_SECRET;
if (!secret) throw new Error("SESSION_SECRET must be set");
const { db } = scriptDb();

const hash = (t: string) => createHmac("sha256", secret).update(t).digest("hex");
const token = () => randomBytes(32).toString("base64url");
const ymd = (d: Date) => d.toISOString().slice(0, 10);

const OWNER_EMAIL = (process.env.SEED_OWNER_EMAIL ?? "owner@example.com").toLowerCase();

/** Smallest valid one-page PDF with a line of text, so the preview has something to show. */
function samplePdf(title: string): Buffer {
  const text = `BT /F1 28 Tf 72 700 Td (${title.replace(/[()\\]/g, "")}) Tj ET\nBT /F1 12 Tf 72 670 Td (Demo proof generated by the Approval Hub seed script.) Tj ET`;
  const objs = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${text.length} >>\nstream\n${text}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let out = "%PDF-1.4\n";
  const offsets: number[] = [];
  objs.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) out += `${String(off).padStart(10, "0")} 00000 n \n`;
  out += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(out, "latin1");
}

async function upsertUser(email: string, name: string, role: schema.UserRole) {
  const [u] = await db
    .insert(users)
    .values({ email, name, role })
    .onConflictDoUpdate({ target: users.email, set: { name, role } })
    .returning();
  return u;
}

async function main() {
  console.log("Seeding…");
  const owner = await upsertUser(OWNER_EMAIL, "Sarah Marketing", "owner");
  const designer = await upsertUser("designer@example.com", "Dana Designer", "designer");
  const ceo = await upsertUser("ceo@example.com", "Chris Executive", "approver");
  const compliance = await upsertUser("compliance@example.com", "Casey Compliance", "approver");
  const agent = await upsertUser("agent@example.com", "Alex Agent", "approver");

  await db
    .insert(settings)
    .values({ key: "app", value: { defaults: { reviewWindowDays: 3, plannedRounds: 3, revisionDays: 2 }, reminders: { halfwayEnabled: true, dueDateEnabled: true }, autoCompleteOnApproval: false } })
    .onConflictDoNothing();

  // Clean previous demo projects so the seed is idempotent.
  const old = await db.select({ id: projects.id }).from(projects).where(eq(projects.createdBy, owner.id));
  for (const p of old) await db.delete(projects).where(eq(projects.id, p.id));

  const today = new Date();

  // Project 1: in review, with a v1 that got change requests and a v2 awaiting approvals.
  const [p1] = await db
    .insert(projects)
    .values({
      name: "Fall auto mailer",
      description: "Direct-mail postcard to current auto policyholders promoting the bundle discount. 6x9, two-sided.",
      startDate: ymd(subDays(today, 9)),
      dueDate: ymd(addDays(today, 9)),
      estHours: 12,
      plannedRounds: 3,
      reviewWindowDays: 3,
      revisionDays: 2,
      designerId: designer.id,
      createdBy: owner.id,
      status: "in_review",
    })
    .returning();
  const [it1] = await db.insert(items).values({ projectId: p1.id, title: "Postcard PDF", type: "file" }).returning();

  const blobToken = process.env.BLOB_READ_WRITE_TOKEN;
  async function fileFor(name: string, title: string) {
    if (!blobToken) return { fileUrl: null as string | null, fileName: name, mime: "application/pdf", size: null as number | null };
    const buf = samplePdf(title);
    const blob = await put(`items/${it1.id}/seed/${name}`, buf, { access: "private", contentType: "application/pdf", addRandomSuffix: true, token: blobToken });
    return { fileUrl: blob.url, fileName: name, mime: "application/pdf", size: buf.length };
  }

  const v1File = await fileFor("fall-auto-mailer-v1.pdf", "Fall Auto Mailer v1");
  const [v1] = await db
    .insert(versions)
    .values({ itemId: it1.id, number: 1, note: "First draft for review", uploadedBy: designer.id, createdAt: subDays(today, 6), ...v1File })
    .returning();
  const [r1] = await db
    .insert(reviewRounds)
    .values({ versionId: v1.id, status: "superseded", sentAt: subDays(today, 6), dueAt: subDays(today, 3), createdAt: subDays(today, 6) })
    .returning();
  const [a1ceo, a1comp, a1agent] = await db
    .insert(approvals)
    .values([
      { roundId: r1.id, userId: ceo.id, status: "approved", decidedAt: subDays(today, 5), lastEmailedAt: subDays(today, 6), tokenHash: hash(token()) },
      { roundId: r1.id, userId: compliance.id, status: "changes_requested", decidedAt: subDays(today, 4), lastEmailedAt: subDays(today, 6), tokenHash: hash(token()) },
      { roundId: r1.id, userId: agent.id, status: "waiting", lastEmailedAt: subDays(today, 4), reminderCount: 1, tokenHash: hash(token()) },
    ])
    .returning();
  void a1ceo;
  void a1agent;
  await db.insert(comments).values([
    { approvalId: a1comp.id, versionId: v1.id, authorId: compliance.id, body: "Page 2: the disclosure text must include the Idaho DOI license number.", pageNo: 2, createdAt: subDays(today, 4) },
    { approvalId: a1comp.id, versionId: v1.id, authorId: compliance.id, body: "Headline says 'guaranteed savings' — please change to 'potential savings'.", pageNo: 1, createdAt: subDays(today, 4) },
  ]);

  const v2File = await fileFor("fall-auto-mailer-v2.pdf", "Fall Auto Mailer v2");
  const [v2] = await db
    .insert(versions)
    .values({ itemId: it1.id, number: 2, note: "Added DOI license number, softened headline per compliance", uploadedBy: designer.id, createdAt: subDays(today, 2), ...v2File })
    .returning();
  const [r2] = await db.insert(reviewRounds).values({ versionId: v2.id, status: "pending", sentAt: subDays(today, 2), dueAt: addDays(today, 1), createdAt: subDays(today, 2) }).returning();
  const demoToken = token();
  await db.insert(approvals).values([
    { roundId: r2.id, userId: ceo.id, status: "approved", decidedAt: subDays(today, 1), lastEmailedAt: subDays(today, 2), tokenHash: hash(token()) },
    { roundId: r2.id, userId: compliance.id, status: "waiting", lastEmailedAt: subDays(today, 2), tokenHash: hash(demoToken) },
    { roundId: r2.id, userId: agent.id, status: "waiting", lastEmailedAt: subDays(today, 2), tokenHash: hash(token()) },
  ]);

  await db.insert(activity).values([
    { projectId: p1.id, actorId: owner.id, type: "project_created", createdAt: subDays(today, 9) },
    { projectId: p1.id, itemId: it1.id, actorId: owner.id, type: "item_created", meta: { title: it1.title }, createdAt: subDays(today, 9) },
    { projectId: p1.id, itemId: it1.id, versionId: v1.id, actorId: designer.id, type: "version_uploaded", meta: { versionNumber: 1, note: v1.note }, createdAt: subDays(today, 6) },
    { projectId: p1.id, itemId: it1.id, versionId: v1.id, actorId: designer.id, type: "round_sent", meta: { versionNumber: 1, count: 3 }, createdAt: subDays(today, 6) },
    { projectId: p1.id, itemId: it1.id, versionId: v1.id, actorId: ceo.id, type: "approver_approved", meta: { versionNumber: 1 }, createdAt: subDays(today, 5) },
    { projectId: p1.id, itemId: it1.id, versionId: v1.id, actorId: compliance.id, type: "approver_changes_requested", meta: { versionNumber: 1 }, createdAt: subDays(today, 4) },
    { projectId: p1.id, itemId: it1.id, versionId: v1.id, actorId: owner.id, type: "nudged", meta: { target: agent.email }, createdAt: subDays(today, 4) },
    { projectId: p1.id, itemId: it1.id, versionId: v2.id, actorId: designer.id, type: "version_uploaded", meta: { versionNumber: 2, note: v2.note }, createdAt: subDays(today, 2) },
    { projectId: p1.id, itemId: it1.id, versionId: v2.id, actorId: designer.id, type: "round_superseded", meta: { versionNumber: 2 }, createdAt: subDays(today, 2) },
    { projectId: p1.id, itemId: it1.id, versionId: v2.id, actorId: designer.id, type: "round_sent", meta: { versionNumber: 2, count: 3 }, createdAt: subDays(today, 2) },
    { projectId: p1.id, itemId: it1.id, versionId: v2.id, actorId: ceo.id, type: "approver_approved", meta: { versionNumber: 2 }, createdAt: subDays(today, 1) },
  ]);

  // Project 2: tracker-only, not started yet.
  const [p2] = await db
    .insert(projects)
    .values({
      name: "Q4 agent newsletter",
      description: "Quarterly email to independent agents. Copy from the sales team due first.",
      startDate: ymd(addDays(today, 5)),
      dueDate: ymd(addDays(today, 30)),
      estHours: 6,
      plannedRounds: 2,
      reviewWindowDays: 3,
      revisionDays: 2,
      designerId: designer.id,
      createdBy: owner.id,
      status: "not_started",
    })
    .returning();
  await db.insert(activity).values({ projectId: p2.id, actorId: owner.id, type: "project_created" });

  const appUrl = (process.env.APP_URL ?? "http://localhost:3000").replace(/\/$/, "");
  console.log(`
Seeded.
  Owner (sign in at ${appUrl}/sign-in): ${owner.email}
  Designer: ${designer.email}
  Demo approver link (Casey Compliance on v2): ${appUrl}/review/${demoToken}
  ${blobToken ? "Sample PDFs uploaded to Blob." : "BLOB_READ_WRITE_TOKEN not set — versions have no files (previews show a placeholder)."}
`);
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
